# Generated by Django 3.0.3 on 2020-03-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200324_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeblog',
            name='category',
            field=models.ForeignKey(default='others', on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
