# Generated by Django 3.0.3 on 2020-03-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sidewidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='words',
            field=models.CharField(default='ten', max_length=20),
        ),
        migrations.AlterField(
            model_name='sidewidget',
            name='content',
            field=models.TextField(),
        ),
    ]
