# Generated by Django 3.0.3 on 2020-03-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200328_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='words',
        ),
    ]
